# Generated by Django 2.0.7 on 2018-07-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180730_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=700, verbose_name='访问地址'),
        ),
    ]
