# Generated by Django 2.0.7 on 2018-07-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180730_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(default='', verbose_name='访问地址'),
        ),
    ]
